
//app
export const SET_SAFE_AREA = "SET_SAFE_AREA";
export const SET_BOTTOM_TAB = "SET_BOTTOM_TAB";
export const SET_THEME = 'SET_THEME';
export const SET_IN_CONTROLS_SCREEN = 'SET_IN_CONTROLS_SCREEN';
export const RESET_CONTROLS_SCREEN = 'RESET_CONTROLS_SCREEN';

export const SET_IN_SETTINGS_SCREEN = 'SET_IN_SETTINGS_SCREEN';
export const RESET_SETTINGS_SCREEN = 'RESET_SETTINGS_SCREEN';

export const RESET_STORE = "RESET_STORE";

//user
export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD';
export const USER_UPLOAD_FILE = 'USER_UPLOAD_FILE';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';

export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_USER_DETAILS_DATA = 'SET_USER_DETAILS_DATA';
export const SET_USER_DETAILS_DATA_MEDIA = 'SET_USER_DETAILS_DATA_MEDIA';
export const SET_USER_DETAILS_DATA_SETTINGS = 'SET_USER_DETAILS_DATA_SETTINGS';
export const RESET_USER_DETAILS_DATA = 'RESET_USER_DETAILS_DATA';
export const SET_BLOCKED_PROFILE_IDS = 'SET_BLOCKED_PROFILE_IDS';

export const CREDENTIALS = 'CREDENTIALS';
export const RESET_STATE = 'RESET_STATE';

export const SET_CHAT_PUSHER_STATUS = 'SET_CHAT_PUSHER_STATUS';
export const SET_ACTIVE_SCREEN = 'SET_ACTIVE_SCREEN';

//modals
export const SCORED_FLASHING_MODAL_OPEN = 'SCORED_FLASHING_MODAL_OPEN';
export const SCORED_FLASHING_MODAL_CLOSE = 'SCORED_FLASHING_MODAL_CLOSE';

export const USER_INFO_MODAL_OPEN = 'USER_INFO_MODAL_OPEN';
export const USER_INFO_MODAL_CLOSE = 'USER_INFO_MODAL_CLOSE';

export const GET_PREMIUM_MODAL_OPEN = 'GET_PREMIUM_MODAL_OPEN';
export const GET_PREMIUM_MODAL_CLOSE = 'GET_PREMIUM_MODAL_CLOSE';

export const MATCHING_MODAL_OPEN = 'MATCHING_MODAL_OPEN';
export const MATCHING_MODAL_CLOSE = 'MATCHING_MODAL_CLOSE';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const TUTORIAL_I_MODAL_OPEN = 'TUTORIAL_I_MODAL_OPEN';
export const TUTORIAL_I_MODAL_CLOSE = 'TUTORIAL_I_MODAL_CLOSE';

export const TUTORIAL_II_MODAL_OPEN = 'TUTORIAL_II_MODAL_OPEN';
export const TUTORIAL_II_MODAL_CLOSE = 'TUTORIAL_II_MODAL_CLOSE';

export const TUTORIAL_III_MODAL_OPEN = 'TUTORIAL_III_MODAL_OPEN';
export const TUTORIAL_III_MODAL_CLOSE = 'TUTORIAL_III_MODAL_CLOSE';

export const SHOW_PICTURE_MODAL_OPEN = 'SHOW_PICTURE_MODAL_OPEN';
export const SHOW_PICTURE_MODAL_CLOSE = 'SHOW_PICTURE_MODAL_CLOSE';

export const LOADING_MODAL_OPEN = 'LOADING_MODAL_OPEN';
export const LOADING_MODAL_CLOSE = 'LOADING_MODAL_CLOSE';

export const SHOW_VIDEO_MODAL_OPEN = 'SHOW_VIDEO_MODAL_OPEN';
export const SHOW_VIDEO_MODAL_CLOSE = 'SHOW_VIDEO_MODAL_CLOSE';


export const SHOW_ACCESS_NOT_PERMITTED_MODAL_OPEN = 'SHOW_ACCESS_NOT_PERMITTED_MODAL_OPEN';
export const SHOW_ACCESS_NOT_PERMITTED_MODAL_CLOSE = 'SHOW_ACCESS_NOT_PERMITTED_MODAL_CLOSE';

export const SEARCHING_MATCHES_MODAL_OPEN = 'SEARCHING_MATCHES_MODAL_OPEN';
export const SEARCHING_MATCHES_MODAL_CLOSE = 'SEARCHING_MATCHES_MODAL_CLOSE'


export const NO_MATCHES_MODAL_OPEN = 'NO_MATCHES_MODAL_OPEN';
export const NO_MATCHES_MODAL_CLOSE = 'NO_MATCHES_MODAL_CLOSE'

export const BLOCK_CONTACT_MODAL_OPEN = 'BLOCK_CONTACT_MODAL_OPEN'
export const BLOCK_CONTACT_MODAL_CLOSE = 'BLOCK_CONTACT_MODAL_CLOSE'

export const NO_SCORES_MODAL_OPEN = 'NO_SCORES_MODAL_OPEN';
export const NO_SCORES_MODAL_CLOSE = 'NO_SCORES_MODAL_CLOSE';

export const TERMS_MODAL_OPEN = 'TERMS_MODAL_OPEN';
export const TERMS_MODAL_CLOSE = 'TERMS_MODAL_CLOSE';

